import { notFound } from "next/navigation"; import Link from "next/link"; import { Undo2 } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header"; import { Button } from "@/components/ui/button"; import { ReturnPrintButton } from "@/features/returns/components/print-button"; import { DeletePurchaseReturnButton } from "@/features/returns/components/delete-purchase-return-button"; import { getPurchaseReturnById } from "@/features/returns/queries"; import { formatCurrency } from "@/lib/currency"; import { requirePageAccess } from "@/lib/permissions"; import { getDictionary, getLocale } from "@/i18n/server";
export const dynamic="force-dynamic";
export default async function Page({params}:{params:Promise<{id:string}>}) { await requirePageAccess("RETURNS_VIEW"); const {id}=await params; const [r,t,locale]=await Promise.all([getPurchaseReturnById(id),getDictionary(),getLocale()]); if(!r)notFound();
const methodLabels: Record<string,string> = { CASH: t.returns.cash, BANK_TRANSFER: t.returns.bankTransfer, SUPPLIER_CREDIT: t.returns.supplierCredit, NO_IMMEDIATE_REFUND: t.returns.noImmediateRefund };
const statusLabels: Record<string,string> = { PENDING: t.returns.pending, COMPLETED: t.returns.completed, CREDITED: t.returns.credited, NOT_REQUIRED: t.returns.notRequired };
return <div className="space-y-6"><PageHeader title={`مرتجع ${r.returnNumber}`} icon={Undo2} action={<div className="flex gap-2 print:hidden"><Button variant="outline" nativeButton={false} render={<Link href={`/dashboard/purchases/${r.purchaseId}`}/>}>فاتورة الشراء</Button><ReturnPrintButton/><DeletePurchaseReturnButton id={r.id} returnNumber={r.returnNumber} /></div>}/>
<div className="grid gap-3 rounded-lg border p-5 sm:grid-cols-2 lg:grid-cols-4"><Info l="فاتورة الشراء" v={r.purchase.orderNumber}/><Info l="المورد" v={r.supplier.name}/><Info l="تاريخ المرتجع" v={r.createdAt.toLocaleString(locale)}/><Info l="الموظف" v={r.createdBy.name}/><Info l="السبب" v={r.reason}/><Info l="طريقة التعويض" v={methodLabels[r.refundMethod]??r.refundMethod}/><Info l="حالة التعويض" v={statusLabels[r.refundStatus]??r.refundStatus}/><Info l="المبلغ" v={formatCurrency(Number(r.refundAmount),locale)}/></div>
<div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted/50"><tr>{["المنتج","SKU","Barcode","الكمية","تكلفة الوحدة","الإجمالي","السبب"].map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody>{r.items.map(i=><tr key={i.id} className="border-t"><td className="p-3">{i.product.name}</td><td className="p-3">{i.product.sku}</td><td className="p-3">{i.product.barcode??"—"}</td><td className="p-3">{i.quantity}</td><td className="p-3">{formatCurrency(Number(i.unitCost),locale)}</td><td className="p-3">{formatCurrency(Number(i.total),locale)}</td><td className="p-3">{i.reason??r.reason}</td></tr>)}</tbody></table></div>{r.notes&&<p className="rounded-lg border p-4"><b>ملاحظات: </b>{r.notes}</p>}</div> }
function Info({l,v}:{l:string;v:string}){return <div><p className="text-xs text-muted-foreground">{l}</p><p className="font-medium">{v}</p></div>}
