"use client";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { Loader2, Minus, Plus, Wallet } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea";
import { adjustSupplierBalance } from "../actions"; import { useLocale } from "@/i18n/locale-provider"; import { formatCurrency } from "@/lib/currency";
export function AdjustSupplierBalanceDialog({supplierId,currentBalance}:{supplierId:string;currentBalance:number}) {
 const {t,locale}=useLocale(); const [open,setOpen]=useState(false); const [increase,setIncrease]=useState(true); const [amount,setAmount]=useState(0); const [note,setNote]=useState(""); const [pending,startTransition]=useTransition(); const next=currentBalance+(increase?amount:-amount);
 function submit(){startTransition(async()=>{const result=await adjustSupplierBalance(supplierId,{delta:increase?amount:-amount,note:note.trim()||undefined});if(result.error){toast.error(result.error);return;}toast.success(t.suppliers.balanceAdjusted);setOpen(false);setAmount(0);setNote("");});}
 return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button variant="outline" size="sm"><Wallet className="size-4"/>{t.suppliers.adjustBalance}</Button>}/><DialogContent><DialogHeader><DialogTitle>{t.suppliers.adjustBalance}</DialogTitle><DialogDescription>{t.suppliers.adjustBalanceDescription}</DialogDescription></DialogHeader><div className="space-y-4"><div className="grid grid-cols-2 gap-2"><Button variant={increase?"default":"outline"} onClick={()=>setIncrease(true)}><Plus className="size-4"/>{t.suppliers.increaseBalance}</Button><Button variant={!increase?"destructive":"outline"} onClick={()=>setIncrease(false)}><Minus className="size-4"/>{t.suppliers.decreaseBalance}</Button></div><div className="space-y-2"><Label>{t.suppliers.adjustmentAmount}</Label><Input type="number" min="0" step="0.01" value={amount||""} onChange={e=>setAmount(Math.max(0,e.target.valueAsNumber||0))}/></div><div className="space-y-2"><Label>{t.suppliers.adjustmentNote}</Label><Textarea value={note} onChange={e=>setNote(e.target.value)}/></div><div className="flex justify-between rounded-lg border bg-muted/30 p-3 text-sm"><span>{t.suppliers.currentBalance}: <b>{formatCurrency(currentBalance,locale)}</b></span><span>{t.suppliers.balanceAfterAdjustment}: <b>{formatCurrency(next,locale)}</b></span></div><Button className="w-full" disabled={pending||amount<=0||next<0} onClick={submit}>{pending&&<Loader2 className="size-4 animate-spin"/>}{t.common.save}</Button></div></DialogContent></Dialog>;
}
