import { notFound } from "next/navigation"; import Link from "next/link"; import { RotateCcw } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header"; import { Button } from "@/components/ui/button"; import { Badge } from "@/components/ui/badge"; import { ReturnPrintButton } from "@/features/returns/components/print-button"; import { DeleteSalesReturnButton } from "@/features/returns/components/delete-sales-return-button"; import { getSalesReturnById } from "@/features/returns/queries"; import { getSystemSettings } from "@/features/settings/queries"; import { DocumentBrandHeader } from "@/components/shared/document-brand-header"; import { formatCurrency } from "@/lib/currency"; import { requirePageAccess } from "@/lib/permissions"; import { getDictionary, getLocale } from "@/i18n/server";
export const dynamic="force-dynamic";
export default async function Page({params}:{params:Promise<{id:string}>}) { await requirePageAccess("RETURNS_VIEW"); const {id}=await params; const [r,t,locale,settings]=await Promise.all([getSalesReturnById(id),getDictionary(),getLocale(),getSystemSettings()]); if(!r)notFound();
const methodLabels: Record<string,string> = { CASH: t.returns.cash, CARD: t.returns.card, BANK_TRANSFER: t.returns.bankTransfer, CUSTOMER_CREDIT: t.returns.customerCredit, NO_IMMEDIATE_REFUND: t.returns.noImmediateRefund };
const statusLabels: Record<string,string> = { PENDING: t.returns.pending, COMPLETED: t.returns.completed, CREDITED: t.returns.credited, NOT_REQUIRED: t.returns.notRequired };
const conditionLabels: Record<string,string> = { GOOD: t.returns.good, DAMAGED: t.returns.damaged, DEFECTIVE: t.returns.defective };
return <div className="space-y-6"><DocumentBrandHeader logoUrl={settings.logoUrl} name={settings.appName} title="مرتجع" reference={r.returnNumber} date={r.createdAt.toLocaleString(locale)}/><PageHeader title={`مرتجع ${r.returnNumber}`} icon={RotateCcw} action={<div className="flex gap-2 print:hidden"><Button variant="outline" nativeButton={false} render={<Link href={`/dashboard/invoices/${r.invoiceId}`}/>}>الفاتورة الأصلية</Button><ReturnPrintButton/><DeleteSalesReturnButton id={r.id} returnNumber={r.returnNumber} /></div>}/>
<div className="grid gap-3 rounded-lg border p-5 sm:grid-cols-2 lg:grid-cols-4"><Info l="الفاتورة" v={r.invoice.invoiceNumber}/><Info l="العميل" v={r.invoice.customerName}/><Info l="تاريخ المرتجع" v={r.createdAt.toLocaleString(locale)}/><Info l="الموظف" v={r.createdBy.name}/><Info l="السبب" v={r.reason}/><Info l="طريقة الاسترداد" v={methodLabels[r.refundMethod]??r.refundMethod}/><Info l="حالة الاسترداد" v={statusLabels[r.refundStatus]??r.refundStatus}/><Info l="المبلغ المسترد" v={formatCurrency(Number(r.refundAmount),locale)}/></div>
<div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted/50"><tr>{["المنتج","SKU","Barcode","الكمية","سعر الوحدة","الإجمالي","الحالة","إعادة للمخزون"].map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody>{r.items.map(i=><tr key={i.id} className="border-t"><td className="p-3">{i.invoiceItem.name}</td><td className="p-3">{i.product?.sku??"—"}</td><td className="p-3">{i.product?.barcode??"—"}</td><td className="p-3">{Number(i.quantity)}</td><td className="p-3">{formatCurrency(Number(i.unitPrice),locale)}</td><td className="p-3">{formatCurrency(Number(i.total),locale)}</td><td className="p-3"><Badge variant="outline">{conditionLabels[i.condition]??i.condition}</Badge></td><td className="p-3">{i.restock?t.returns.yes:t.returns.no}</td></tr>)}</tbody></table></div>{r.notes&&<p className="rounded-lg border p-4"><b>ملاحظات: </b>{r.notes}</p>}</div> }
function Info({l,v}:{l:string;v:string}){return <div><p className="text-xs text-muted-foreground">{l}</p><p className="font-medium">{v}</p></div>}
