import { notFound } from "next/navigation"; import Link from "next/link"; import { Undo2 } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header"; import { Button } from "@/components/ui/button"; import { ReturnPrintButton } from "@/features/returns/components/print-button"; import { DeletePurchaseReturnButton } from "@/features/returns/components/delete-purchase-return-button"; import { getPurchaseReturnById } from "@/features/returns/queries"; import { getSystemSettings } from "@/features/settings/queries"; import { DocumentBrandHeader } from "@/components/shared/document-brand-header"; import { formatCurrency } from "@/lib/currency"; import { requirePageAccess } from "@/lib/permissions"; import { getDictionary, getLocale } from "@/i18n/server";
export const dynamic="force-dynamic";
export default async function Page({params}:{params:Promise<{id:string}>}) { await requirePageAccess("RETURNS_VIEW"); const {id}=await params; const [r,t,locale,settings]=await Promise.all([getPurchaseReturnById(id),getDictionary(),getLocale(),getSystemSettings()]); if(!r)notFound();
const methodLabels: Record<string,string> = { CASH: t.returns.cash, BANK_TRANSFER: t.returns.bankTransfer, SUPPLIER_CREDIT: t.returns.supplierCredit, NO_IMMEDIATE_REFUND: t.returns.noImmediateRefund };
const statusLabels: Record<string,string> = { PENDING: t.returns.pending, COMPLETED: t.returns.completed, CREDITED: t.returns.credited, NOT_REQUIRED: t.returns.notRequired };
return <div className="space-y-6"><DocumentBrandHeader logoUrl={settings.logoUrl} name={settings.appName} title={t.returns.returnLabel} reference={r.returnNumber} date={r.createdAt.toLocaleString(locale)}/><PageHeader title={`${t.returns.returnLabel} ${r.returnNumber}`} icon={Undo2} action={<div className="flex gap-2 print:hidden"><Button variant="outline" nativeButton={false} render={<Link href={`/dashboard/purchases/${r.purchaseId}`}/>}>{t.returns.purchaseInvoice}</Button><ReturnPrintButton/><DeletePurchaseReturnButton id={r.id} returnNumber={r.returnNumber} /></div>}/>
<div className="grid gap-3 rounded-lg border p-5 sm:grid-cols-2 lg:grid-cols-4"><Info l={t.returns.purchaseInvoice} v={r.purchase.orderNumber}/><Info l={t.returns.supplier} v={r.supplier.name}/><Info l={t.returns.returnDate} v={r.createdAt.toLocaleString(locale)}/><Info l={t.returns.employee} v={r.createdBy.name}/><Info l={t.returns.reason} v={r.reason}/><Info l={t.returns.compensationMethod} v={methodLabels[r.refundMethod]??r.refundMethod}/><Info l={t.returns.compensationStatus} v={statusLabels[r.refundStatus]??r.refundStatus}/><Info l={t.returns.amount} v={formatCurrency(Number(r.refundAmount),locale)}/></div>
<div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted/50"><tr>{[t.returns.product,"SKU","Barcode",t.returns.quantity,t.purchases.unitCostLabel,t.returns.total,t.returns.reason].map(h=><th key={h} className="p-3 text-start">{h}</th>)}</tr></thead><tbody>{r.items.map(i=><tr key={i.id} className="border-t"><td className="p-3">{i.product.name}</td><td className="p-3">{i.product.sku}</td><td className="p-3">{i.product.barcode??"—"}</td><td className="p-3">{Number(i.quantity)}</td><td className="p-3">{formatCurrency(Number(i.unitCost),locale,false,4)}</td><td className="p-3">{formatCurrency(Number(i.total),locale)}</td><td className="p-3">{i.reason??r.reason}</td></tr>)}</tbody></table></div>{r.notes&&<p className="rounded-lg border p-4"><b>{t.returns.notes}: </b>{r.notes}</p>}</div> }
function Info({l,v}:{l:string;v:string}){return <div><p className="text-xs text-muted-foreground">{l}</p><p className="font-medium">{v}</p></div>}
